### ISSUE TITLE
Alsamixer scripted setup

### ISSUE THREAD

**Issue by Dloranger** [OpenRepeater/scripts#11]
for ics hardware (and others?), the user must manually set the alsamixer settings.

possible scripted solution referenced here

https://askubuntu.com/questions/97936/terminal-command-to-set-audio-volume

**Comment by Dloranger** [comment]
to set the values (verified)

amixer set 'Headphone' 86%; amixer set 'PCM' 75%; amixer set 'Lineout' 58%; amixer set 'Mic' 59%; amixer set 'Capture Mux' LINE_IN;

should also be able to force save the settings just in-case of an ungraceful shutdown (powerloss)
sudo alsactl store <0?>

**Comment by abcrawford** [comment]
This has been added to the main ORP gui code base as part of the board preset feature. The above mentioned settings are stored in the presets array and past to alsa upon selection of the board.
