### ISSUE TITLE
Purge wolfram* package from the file system

### ISSUE THREAD

**Issue by Dloranger** [OpenRepeater/scripts#13]
This package is bloatware, taking up 700MB, and may cause apt-get upgrade to timeout in odd cases

https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=83491

sudo apt-get purge wolfram*

**Comment by abcrawford** [comment]
This appears to an old post and a non-issue in stretch from my deductions. I tried to removed the packages as suggested on my RC build and told me there was nothing to remove. I also issued "which wolfram" with no results.

**Comment by Dloranger** [comment]
This may only exist in the desktop version of the builds, and not in the
lite versions
