### ISSUE TITLE
Wifi drops during install on Pi Zero

### ISSUE THREAD

**Issue by mytechguyri** [OpenRepeater/scripts#20]
Wifi connection drops during install on Pi zero resulting in install_orp_from_github in the functions.sh and the install of svxlink modules to fail.

**Comment by mytechguyri** [comment]
A patch (provided) to the functions.sh file to check that the network is up before proceeding with the install of the openrepeater web files resolves this issue.

**Comment by Dloranger** [comment]
Even running on a LAN I still encountered a timeout.

Possible solution (see last post at bottom)
https://raspberrypi.stackexchange.com/questions/60195/ssh-fails-after-30-minutes

**Comment by Dloranger** [comment]
I was able to run an install with the updated script successfully, recommend to close

**Comment by mytechguyri** [comment]
Yes, me too... No more wifi drops.

--- Sent from my Android™ powered LG V20

**Comment by alleghenycreative** [comment]
Seems to be resolved from feedback. Closing issue.
