### ISSUE TITLE
Build log has silent fails

### ISSUE THREAD

**Issue by Dloranger** [OpenRepeater/scripts#22]
The logging does not seem to capture failures that occur outside the svxlink build portion of the script.

I believe this stems from an incorrect usage of the redirect to tee command

In the tee portion of the script it looks like the script is not redirecting the stderr to the stdout which seems to be the general construct recommended online.

script is doing
(...) ) | tee /root/orp_install.log

while the recommended approach is to use
... 2>&1 | log.file

**Comment by bobruddy** [comment]
if you have not already i can address this tonight

**Comment by Dloranger** [comment]
I have not dug into this, just a first cut at the possible cause from what I could find as a likely candidate on some of the stackoverflow and such forums.

**Comment by abcrawford** [comment]
This should be fixed now based on @bobruddy recommendation.
