### ISSUE TITLE
Remote Relay Module not found

### ISSUE THREAD

**Issue by bobruddy** [OpenRepeater/scripts#26]
It looks like this repo was renamed and the branch naming was changed from the default "master" to a versioned numbering system. 

I found this after implementing #22 it was one of the silet fails. 

I have a fix in my fork that I'm kicking off on a test now. If that is successful I'll open a pull request.

The only files that are installed are RemoteRelay.tcl ModuleRemoteRelay.tcl. If more files need to be installed. Either let me know or someone can modify my fix afterwards to add the additional files. 

I also assumed that the 1.1 branch is the one you would like to use. I put a BRANCH variable in the install script.

**Comment by abcrawford** [comment]
I'm debating if we should remove remote relay from the script so that it is not installed by default. As of 2.1.0 with the new module framework. This can be easily installed from the new download page if required by the user. The svxlink card boards in the presets have built in relays which I can load defaults for, so that is only reservation. I haven't fully tested that yet.

**Comment by bobruddy** [comment]
I just tested your module install through the interface. It works very much as expected and was very simple. 

The only improvements that I'd suggest for a future iteration over the new module install. Would be for the system to list out the "known" modules right under the installed one. The difference is where you have "Activate | Delete" for those uninstalled ones you'd have an "Install" and it would download and install it. 

Another next version feature would be to be able to-do updates right from there. Sort of how wordpress works.

**Comment by abcrawford** [comment]
Thanks for the feedback @bobruddy. Yeah I was talking about that with Dan while I was implementing it. The module framework is modeled after WordPress plugins. I don't think that I would have a listing of available modules on the same page. It would either be a separate linked page or light box. It would dynamically have to display them to allow for additions which would be a function on the main site as well. So I would need to come up with some sort of API or RSS feed. I also need to build a function that checks for internet access and only allows features like this to be accessible if connected to the outside internet. There will be sites that are remote and may have networking for management, but not internet.

**Comment by abcrawford** [comment]
Just removed/depreciated install of ORP remote relay module. This must be downloaded and installed separately. I've left the function there for now, the call to it is just commented out if someone wishes to use it. I've updated the function to reflect the rename if that happens.
