### ISSUE TITLE
In ports.php Advanced Details is an empty window

### ISSUE THREAD

**Issue by bobruddy** [OpenRepeater/scripts#28]
Configuration: Raspberry PI 3, ics-ctrl 2x, 2.1.x install 

When clicking on the advanced details button at the bottom of the screen an empty box shows up. See screen recording attached. 

[Screen Recording 2019-02-05 at 10.13.56 PM.zip](https://github.com/OpenRepeater/scripts/files/2834745/Screen.Recording.2019-02-05.at.10.13.56.PM.zip)

**Comment by abcrawford** [comment]
Good catch. Please repost this over on the issues for https://github.com/OpenRepeater/openrepeater as it applies to that repo and not the build script.

**Comment by bobruddy** [comment]
done
