### ISSUE TITLE
automatically  force the sd card to expand after script completes

### ISSUE THREAD

**Issue by Dloranger** [OpenRepeater/scripts#34]
https://www.raspberrypi.org/forums/viewtopic.php?t=174434

should be a good starting point

**Comment by ghost** [comment]
Bullseye does this.

**Comment by abcrawford** [comment]
My post build imaging script (private repo) also takes care of this. This is the script I created for making the distributed IMG files. It has to be run with the SD card build to be made into an IMG file on a Debian Linux based computer (I use Mint). It will not only take care of all the things my previous Automator script took care of, but it will shrink the image size to as small as it can be made (a problem we were having issues figuring out previously) and then it will mount the IMG file and restore the auto expand present on the first boot of Raspberry Pi OS prior to zipping the file. Then when the end user downloads and burns the card. They will be able to burn it to whatever size card they want and when they boot it will expand to fill their card size.

**Comment by ghost** [comment]
close

**Comment by Dloranger** [comment]
Closing as now a built in feature of the OS
