### ISSUE TITLE
Update ICS ADC to use the 12 bit driver instead of the 10 bit driver

### ISSUE THREAD

**Issue by Dloranger** [OpenRepeater/scripts#35]
https://github.com/OpenRepeater/scripts/blob/2.1.2/functions/functions.sh#L290-L291

replace existing 10 bit driver code
#Enable mcp3008 adc overlay
dtoverlay=mcp3008:spi0-0-present,spi0-0-speed=3600000

with the 12 bit callout
#Enable mcp3208 adc overlay
dtoverlay=mcp3202:spi0-0-present,spi0-0-speed=3600000

**Comment by Dloranger** [comment]
This change will give the 12bit accuracy, but inadvertantly sets it to give only 2 channels instead of 8

**Comment by ghost** [comment]
close

**Comment by Dloranger** [comment]
Confirmed change - https://github.com/OpenRepeater/scripts/blob/3.0.x-DEV/functions/functions_ics.sh#L30
