### ISSUE TITLE
Disable Bluetooth for reduced power consumption

### ISSUE THREAD

**Issue by Dloranger** [OpenRepeater/scripts#38]
I noticed in the system boot logs the bluetooth is left active.  I think this should be disabled for reduced power consumption.  

add to /boot/config.txt

dtoverlay=disable-bt

**Comment by abcrawford** [comment]
OK, worth considering. Just wondering if it would have the converse affect to those that want to use it and are wondering why it isn't working. Might have to give an option somewhere else to disable it which might take more work.

**Comment by Dloranger** [comment]
I think for our audience the use of BT is highly unlikely, my opinion, but I dont see the use of BT in a repeater setup being wide spread

**Comment by abcrawford** [comment]
I agree with the repeater use sentiment. There are users that use ORP as a node as well. Just trying to think it through. Have you metered it on your end to see if there is any significant power savings? I am just trying to decide if it would be better suited to write something like an "eco mode" script. Maybe make it part of ORP helper where you could run a command to disable or enable. Maybe include other items such as Wifi as well.

**Comment by Dloranger** [comment]
I havent metered it, but an eco mode is an interesting idea, we could kill
hdmi (already do I believe), bluetooth, leds, throttle processor, etc.
Lots of guides out there for doing minimum power usage

**Comment by ghost** [comment]
I added disable BT but will make a script they can run to re-enable it when needed.

**Comment by ghost** [comment]
close

**Comment by Dloranger** [comment]
Confirmed in code
https://github.com/OpenRepeater/scripts/blob/3.0.x-DEV/functions/functions_rpi.sh#L69-L82
