### ISSUE TITLE
Update MCP3208 clocking speed

### ISSUE THREAD

**Issue by Dloranger** [OpenRepeater/scripts#39]
The current setting in /boot/config.txt is 3.6MHz, but the datasheet has a maximum of 2MHZ, suggest to set it to 1MHz to ensure proper operation

**Comment by ghost** [comment]
close

**Comment by Dloranger** [comment]
Not fixed yet

https://github.com/OpenRepeater/scripts/blob/3.0.x-DEV/functions/functions_ics.sh#L30 still shows 3.6MHZ

**Comment by Dloranger** [comment]
fixed in PR #67
