### ISSUE TITLE
3.0 - Need to install libjsoncpp-dev to support trunk builds

### ISSUE THREAD

**Issue by Dloranger** [OpenRepeater/scripts#40]
New dependency needs to be installed

**Comment by abcrawford** [comment]
Elaborate if you happen to know what it will be for. That will help when we get to that stage.

**Comment by Dloranger** [comment]
Its a build dependency now so without it you cant build svxlink from source (trunk only so far).

From what I can find, it appears to be related to analog talk group feature that was merged

**Comment by ghost** [comment]
close

**Comment by Dloranger** [comment]
Confirmed in code
https://github.com/OpenRepeater/scripts/blob/3.0.x-DEV/functions/functions_svxlink.sh#L27
