### ISSUE TITLE
Tune php-fpm pool

### ISSUE THREAD

**Issue by mathewpeterson** [OpenRepeater/scripts#6]
Currently on the beta image, there are ~200 php5-cgi processes that get spawned on boot.

**Comment by mathewpeterson** [comment]
It looks like this comes from the lighttpd config: https://github.com/OpenRepeater/scripts/blob/master/repeater_build.sh#L151

**Comment by ghost** [comment]
No I wrote the config it should only be spawning 4 processed

r.e.neese

**Comment by mathewpeterson** [comment]
I linked to the line of the Lighttpd config where it spawns 5 main and 40 sub processes for a total of 200.

Currently there seems to be a divergence between the two build scripts (e.g. one uses nginx and the other uses lighttpd) so I'm sure this will get reconciled soon. I just wanted to flag this since we are running on low resource machines.

**Comment by ghost** [comment]
I have not had time to rewrite the install scipt that builds from source.
As I have been more focused on pkg based installs. And trying to get the
prevail imgs for boards done. Having moved as 2 issues at hand I only have
the pi2 to work with. So been working on trying to get raspbian up to par
and working only to find driver conflicts with on board usb nic and usb
sound cards.

There is a raspbian Jessie img on the repo server. And it's a no X img .
And I have a install script for it to push up .

When I get home tomorrow I will work on pushing it up and the image I have
based on it with my new she'll menu.

And it should work with our new board when we have one to test. .

Raspbian does not officially support Jessie yet. They say it's going to be
c a little longer

**Comment by ghost** [comment]
I will work on running the php more. And yes moved over to nginx as I know
it better then lighttpd. So with building a install script I can support
and maintain it was easier

**Comment by mathewpeterson** [comment]
Fair enough. I have a pi 1 b so let me know if there's anything I can do to help.

**Comment by rneese45** [comment]
My cell is 219 276  1070. I need a bit of time but can walk u through
adapting my script to be a build it script.  The only issue currently is I
only have Jessie pkgs so adapting for older boards will take work .no u ha
pi b ob b+ ?

**Comment by mathewpeterson** [comment]
I have the original Raspberry Pi B model. 

Just an FYI, you posted your number to a publicly visible page.

**Comment by ghost** [comment]
I thought u emailed me directly. O well. 700 256 model then right.

**Comment by mathewpeterson** [comment]
I believe it has 512mb of RAM.

Let's take this conversation to email and go from there.

**Comment by ghost** [comment]
Ok it looks like my tuning for php fell out of the install script. When I
get home  I will return the php and put it in the script.. I do tune down
nginx to 4 processes.

**Comment by ghost** [comment]
Email me direct

**Comment by ghost** [comment]
The build from src install my sql no mm longer used we moved to sqlite

**Comment by ghost** [comment]
Have u tried the pkg based install ?
