### ISSUE TITLE
Script dies in endless loop

### ISSUE THREAD

**Issue by abcrawford** [OpenRepeater/scripts#75]
![image](https://user-images.githubusercontent.com/7361872/229385569-7f5ea1f7-a760-47ea-8d45-6d92e18007b9.png)
3.0.x-DEV version of script dies.

**Comment by abcrawford** [comment]
Possibly the same as #60

**Comment by AD0ND** [comment]
I enabled the WLAN prior to running the script using RASPI-CONFIG
then ran the wlan drop reconnect line from #60 as referenced above, this allowed the script to complete.

**Comment by abcrawford** [comment]
@AD0ND Thanks for your comment. I will leave this open for evaluation when debuting of the script is underway or for others with the same issue with this version.

**Comment by Dloranger** [comment]
Just ran into this again so even now its still flaky. need to find a better way, but also need to understand why it broken

**Comment by Dloranger** [comment]
I have done several express builds recently and have not encountered this problem again.  It seems to have been resolved.
