### ISSUE TITLE
on install svxlink-source, we should be able to disable remotetrx portion of the build for efficiency

### ISSUE THREAD

**Issue by Dloranger** [OpenRepeater/scripts#8]
Maybe mark as feature request?

**Comment by abcrawford** [comment]
I believe that would have to be done in the current line 117
`cmake -DCMAKE_INSTALL_PREFIX=/usr -DSYSCONF_INSTALL_DIR=/etc -DLOCAL_STATE_DIR=/var -DUSE_QT=no ..`
I am not certain what the switch for that would be. 

That is something we will need to visit in the future as we will probably need to build out some variables and construct the cmake string. 

If you figure it out, post back here so we have a spring board to work off of.

**Comment by Dloranger** [comment]
As remoted trx is becoming more popular, thinking there is no harm in leaving it in at this point.  Closing this issue as no longer needed.
