### ISSUE TITLE
Missing command to create svxlink user when installing svxlink from source

### ISSUE THREAD

**Issue by Dloranger** [OpenRepeater/scripts#9]
https://github.com/OpenRepeater/scripts/blob/2.x.x/functions/functions.sh#L120

Somewhere before the command "make install" the command 

useradd -r -g daemon svxlink

needs to be run or the make install will fail for unknown user

**Comment by abcrawford** [comment]
I had usermod line, but after the make install. I was missing the user add. I grouped these commands together and moved them above the cmake and make install section. With my initial testing I do not see any failures in the make install. Thanks for the valuable feedback.
